//
study(title="Market B  Stock Market", shorttitle=" B  Stock Market")
n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")
 
ap = hlc3 
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)
 
wt1 = tci
wt2 = sma(wt1,4)

plot(0, color=gray)
plot(obLevel1, color=#df5462)
plot(osLevel1, color=#3fcc76)
plot(obLevel2, color=#df5462)
plot(osLevel2, color=#3fcc76)

plot(wt1,style=area, color=#90caf9, title="wt1",  transp=10)
plot(wt2, style=area, color=#2761b3, title="wt2", transp=10)

plot(wt1-wt2, color=yellow, style=line, transp=15)
//plot(cross(wt1, wt2) ? wt2 : na, color =black, style = line, linewidth = 2)


plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red: lime) , style = circles, linewidth = 3)



// barcolor(cross(wt1, wt2) ? (wt2 - wt1 > 0 ? black : yellow) : na)


